% Beale function
beale = @(x) (1.5 - x(1) + x(1)*x(2))^2 + ...
             (2.25 - x(1) + x(1)*x(2)^2)^2 + ...
             (2.625 - x(1) + x(1)*x(2)^3)^2;

% Initial point (far from the minimum)
x0 = [1; 1];

% Optimization options
options = optimoptions('fminunc',...
    'Algorithm','quasi-newton',...
    'Display','iter',...
    'OutputFcn',@bealeout,...
    'PlotFcn',@optimplotfval,...
    'MaxIterations',100,...
    'MaxFunctionEvaluations',500,...
    'StepTolerance',1e-10,...
    'OptimalityTolerance',1e-8);

% Optimization launch
tic;
[x_opt,fval,exitflag,output] = fminunc(beale,x0,options);
time = toc;

% Results
fprintf('\n=== Final Results ===\n')
fprintf('Optimal point: [%.8f, %.8f]\n',x_opt)
fprintf('Function value: %.12f\n',fval)
fprintf('Iterations: %d\n',output.iterations)
fprintf('Function evaluations: %d\n',output.funcCount)
fprintf('Execution time: %.2f seconds\n',time)
